module.exports = {
	DEXPairContract: {
		abi: {
			"ABI version": 2,
			header: ["pubkey", "time", "expire"],
			functions: [
				{
					name: "constructor",
					inputs: [
						{name: "souintA", type: "uint256"},
						{
							name: "souintB",
							type: "uint256",
						},
						{name: "gramsDeployConnector", type: "uint128"},
						{
							name: "gramsDeployWallet",
							type: "uint128",
						},
					],
					outputs: [],
				},
				{
					name: "getConnectorAddress",
					inputs: [
						{name: "_answer_id", type: "uint32"},
						{name: "connectorSoArg", type: "uint256"},
					],
					outputs: [{name: "value0", type: "address"}],
				},
				{
					name: "connectCallback",
					inputs: [{name: "wallet", type: "address"}],
					outputs: [],
				},
				{name: "connect", inputs: [], outputs: []},
				{
					name: "tokensReceivedCallback",
					inputs: [
						{name: "token_wallet", type: "address"},
						{
							name: "token_root",
							type: "address",
						},
						{name: "amount", type: "uint128"},
						{
							name: "sender_public_key",
							type: "uint256",
						},
						{name: "sender_address", type: "address"},
						{
							name: "sender_wallet",
							type: "address",
						},
						{name: "original_gas_to", type: "address"},
						{
							name: "updated_balance",
							type: "uint128",
						},
						{name: "payload", type: "cell"},
					],
					outputs: [],
				},
				{
					name: "burnCallback",
					inputs: [
						{name: "tokens", type: "uint128"},
						{
							name: "payload",
							type: "cell",
						},
						{name: "sender_public_key", type: "uint256"},
						{
							name: "sender_address",
							type: "address",
						},
						{name: "wallet_address", type: "address"},
						{name: "send_gas_to", type: "address"},
					],
					outputs: [],
				},
				{
					name: "getBalance",
					inputs: [{name: "_answer_id", type: "uint32"}],
					outputs: [{name: "value0", type: "uint128"}],
				},
				{
					name: "rootDEX",
					inputs: [],
					outputs: [{name: "rootDEX", type: "address"}],
				},
				{
					name: "soUINT",
					inputs: [],
					outputs: [{name: "soUINT", type: "uint256"}],
				},
				{
					name: "creator",
					inputs: [],
					outputs: [{name: "creator", type: "address"}],
				},
				{
					name: "codeDEXConnector",
					inputs: [],
					outputs: [{name: "codeDEXConnector", type: "cell"}],
				},
				{
					name: "rootA",
					inputs: [],
					outputs: [{name: "rootA", type: "address"}],
				},
				{
					name: "rootB",
					inputs: [],
					outputs: [{name: "rootB", type: "address"}],
				},
				{
					name: "rootAB",
					inputs: [],
					outputs: [{name: "rootAB", type: "address"}],
				},
				{
					name: "walletReserve",
					inputs: [],
					outputs: [{name: "walletReserve", type: "map(address,address)"}],
				},
				{
					name: "syncStatus",
					inputs: [],
					outputs: [{name: "syncStatus", type: "map(address,bool)"}],
				},
				{
					name: "balanceReserve",
					inputs: [],
					outputs: [{name: "balanceReserve", type: "map(address,uint128)"}],
				},
				{
					name: "totalSupply",
					inputs: [],
					outputs: [{name: "totalSupply", type: "uint128"}],
				},
				{
					name: "processingStatus",
					inputs: [],
					outputs: [
						{name: "processingStatus", type: "map(address,map(address,bool))"},
					],
				},
				{
					name: "processingData",
					inputs: [],
					outputs: [
						{name: "processingData", type: "map(address,map(address,uint128))"},
					],
				},
				{
					name: "processingDest",
					inputs: [],
					outputs: [
						{name: "processingDest", type: "map(address,map(address,address))"},
					],
				},
				{
					name: "rootConnector",
					inputs: [],
					outputs: [{name: "rootConnector", type: "map(address,address)"}],
				},
				{
					name: "connectors",
					inputs: [],
					outputs: [
						{
							components: [
								{name: "root_address", type: "address"},
								{
									name: "souint",
									type: "uint256",
								},
								{name: "status", type: "bool"},
							],
							name: "connectors",
							type: "map(address,tuple)",
						},
					],
				},
				{
					name: "counterCallback",
					inputs: [],
					outputs: [{name: "counterCallback", type: "uint256"}],
				},
				{
					name: "callbacks",
					inputs: [],
					outputs: [
						{
							components: [
								{name: "token_wallet", type: "address"},
								{
									name: "token_root",
									type: "address",
								},
								{name: "amount", type: "uint128"},
								{
									name: "sender_public_key",
									type: "uint256",
								},
								{name: "sender_address", type: "address"},
								{
									name: "sender_wallet",
									type: "address",
								},
								{name: "original_gas_to", type: "address"},
								{
									name: "updated_balance",
									type: "uint128",
								},
								{name: "payload_arg0", type: "uint8"},
								{
									name: "payload_arg1",
									type: "address",
								},
								{name: "payload_arg2", type: "address"},
								{
									name: "payload_arg3",
									type: "uint128",
								},
								{name: "payload_arg4", type: "uint128"},
							],
							name: "callbacks",
							type: "map(uint256,tuple)",
						},
					],
				},
			],
			data: [
				{key: 1, name: "rootDEX", type: "address"},
				{
					key: 2,
					name: "soUINT",
					type: "uint256",
				},
				{key: 3, name: "creator", type: "address"},
				{
					key: 4,
					name: "codeDEXConnector",
					type: "cell",
				},
				{key: 5, name: "rootA", type: "address"},
				{
					key: 6,
					name: "rootB",
					type: "address",
				},
				{key: 7, name: "rootAB", type: "address"},
			],
			events: [
				{
					name: "Swap",
					inputs: [
						{name: "swapIn", type: "uint128"},
						{
							name: "swapOut",
							type: "uint128",
						},
						{name: "reserveAfterIn", type: "uint128"},
						{
							name: "reserveAfterOut",
							type: "uint128",
						},
						{name: "rootIn", type: "address"},
						{name: "dexClient", type: "address"},
					],
					outputs: [],
				},
				{
					name: "ProvideLiquidity",
					inputs: [
						{name: "provideA", type: "uint128"},
						{
							name: "provideB",
							type: "uint128",
						},
						{name: "reserveAfterA", type: "uint128"},
						{
							name: "reserveAfterB",
							type: "uint128",
						},
						{name: "mintToProvider", type: "uint128"},
						{name: "provider", type: "address"},
					],
					outputs: [],
				},
				{
					name: "ReturnLiquidity",
					inputs: [
						{name: "burnByProvider", type: "uint128"},
						{
							name: "totalSupplyAfter",
							type: "uint128",
						},
						{name: "toProviderA", type: "uint128"},
						{
							name: "toProviderB",
							type: "uint128",
						},
						{name: "reserveAfterA", type: "uint128"},
						{
							name: "reserveAfterB",
							type: "uint128",
						},
						{name: "provider", type: "address"},
					],
					outputs: [],
				},
			],
		},
		tvc: "te6ccgECiAEAJ44AAgE0AwEBAcACAEPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgBCSK7VMg4wMgwP/jAiDA/uMC8guFBgSHAQAFAviNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT4aSHbPNMAAY4agQIA1xgg+QEB0wABlNP/AwGTAvhC4vkQ8qiV0wAB8nri0z8B+EMhufK0IPgjgQPoqIIIG3dAoLnytPhj0x8B+CO88rnTHwHbPPhHbvJ8bwcBaiLQ0wP6QDD4aak4APhEf29xggiYloBvcm1vc3BvdPhk3CHHANwh1w0f8rwh3QHbPPhHbvJ8BwIoIIIQUe9lP7vjAiCCEHtXi/a74wJICAM8IIIQWUEfubvjAiCCEHhUQh+74wIgghB7V4v2uuMCEgsJAuIw0x/4RFhvdfhk0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAAD7V4v2jPFst/yXD7AI4x+EQgbxMhbxL4SVUCbxHIcs9AygBzz0DOAfoC9ACAas9A+ERvFc8LH8t/yfhEbxT7AOLjAH/4Zwp2ACT4RHBvcnBvcYBAb3T4ZPgnbxAEUCCCEGLFruu64wIgghBkOy/CuuMCIIIQbwUweLrjAiCCEHhUQh+64wIPDg0MAVIw0ds8+FQhjhyNBHAAAAAAAAAAAAAAAAA+FRCH4MjOy3/JcPsA3n/4Z4QBUjDR2zz4ViGOHI0EcAAAAAAAAAAAAAAAADvBTB4gyM70AMlw+wDef/hnhAFQMNHbPPhQIY4bjQRwAAAAAAAAAAAAAAAAOQ7L8KDIzs7JcPsA3n/4Z4QDHDD4Qm7jANHbPNs8f/hnhBB2Afz4SfgnbxBopv5gobV/cvsC+FD4T/hRgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4T/hO+FGBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hOyM+RU/cVIs4RAE5VMMjOVSDIzlnIzgHIzs3Nzc3JIcjPhYjOcc8LbiHPFMmBAID7AFsEUCCCEFMU3pS64wIgghBWDfQpuuMCIIIQWQ9/VrrjAiCCEFlBH7m64wJHRkUTA7Qw+EJu4wD6QZXU0dD6QN/6QZXU0dD6QN/XDX+V1NHQ03/f1w3/ldTR0NP/3/pBldTR0PpA3/pBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/U0ds82zx/+GeEFHYC/PgnbxBopv5gobV/cvsC+En4TvhRgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/HBSCONTD4SfhP+FGBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38cF346A3hYVAARfCQTK+Fr4W4EBAPQPjoCOgOIpb1Aob1Enb1Imb1Mlb1Qkb1Ujb1Yib1ch0CDTB/pA+kDTf9N/NlNkb1g3U2NvWTdTYm9aN1Nhb1s3U2BvXDf4WvhbKNs8yVmBAQD0F/h7+FqkIPh6wgpiX14XAyKOgN4kwAGOgN4kwAKOgN5fB1o/GAH+LvhVXIEBC/QKkvQFkW3iJgF/yMoAWYEBC/RByPQAWYEBC/RB+HVT3vhWXIEBC/QKkvQFkW3iJwFcgQEL9AqT1wt/kXDiVQSgtX/Iy39ZgQEL9EHI9ABZgQEL9EH4di74V1yBAQv0CpL0BZFt4iYBLlmBAQv0Esj0AFmBAQv0QRkBsPh3I/hO+FWBAQv0CpL0BZFt4oEBC/QKk9cKAJFw4n+6II4fMCP4T/hVgQEL9AqS9AWRbeKBAQv0CpPXCgCRcOJ/ut6OgI4QI8jPhYjOgG/PQMmBAID7AOIaAuAj+E74VoEBC/QKkvQFkW3igQEL9AqT1wt/kXDiJPhP+FaBAQv0CpL0BZFt4oEBC/QKk9cLf5Fw4vhUwAAgjiow+E74U4EBC/QKk9cLf5Fw4sAAII4TMPhP+FOBAQv0CpPXC3+RcOLAAN/fjoCOgOJbOhsB/l8xIPhP+FOBAQv0CpPXC3+RcOL4TvhTgQEL9AqT1wt/kXDiqYS1fzFTEfhO+FOBAQv0CpPXC3+RcOL4T/hTgQEL9AqT1wt/kXDiqYS1fzFTMLYIXbYI+E74U4EBC/QKk9cLf5Fw4vhP+FOBAQv0CpPXC3+RcOK2CPhO+FOBAQscAtj0CpPXC3+RcOL4T/hTgQEL9AqT1wt/kXDitglccVMSqYwBtX8BIWxBXyJxUxKpjAG1fwEgbEFfJbYIUwKotX9UcSWphLV/oLV/Xye5kSGRIOJTeLmRIpEh4lxs4iHCACCUMCDCAN6OgI6A4lskHQHiyCB5eY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHlVBMsHzs7Lf8t/MSDJVHBZ+E74V4EBC/QKkvQFkW3igQEL9AoeAf6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz5E6+/1Gzst/zMlUcVr4T/hXgQEL9AqS9AWRbeKBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkTr7/UbOy3/MyfhOHwG0+FiBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPhYjOjQSQF9eEAAAAAAAAAAAAAAAAAADAzxYizxTJcPsA+E/4WIEBC/QKIAH+jiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+FiM6NBJAX14QAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wAr+E74VVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh1+E8BXIEBC/QKkvQFkW3iIyEB/gGBAQv0WTDI9ABZgQEL9EH4dfhO+FZcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4dvhPAVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RB+Hb4TvhXXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+Hf4TwEiAfRcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0Qfh3MHBTt3BTr/hP+FeBAQv0CpL0BZFt4oEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfLXAvVhT4TvhXgQEL9AqS9AWRbeKBAQv0CiMAuI4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkEWXed7Oy3/Lf8t/VVDIzst/y3/Lf1nIzst/zc3JLMjPhYjOcc8LbiHPFMmBAID7AF8FAfxTEfhU+E74U4EBC/QKk9cLf5Fw4qmEtX8xUxH4VPhP+FOBAQv0CpPXC3+RcOKphLV/MbYIU0KhtX9TQqG1fyT4TvhTXIEBC/QKk9cLf5Fw4lUCoLV/yMt/WYEBC/RB+HMj+E/4U1yBAQv0CpPXC3+RcOJVAqC1f8jLf1mBAQslAf70Qfhz+FQjoLV/+HRTksjPkcj3EzrLf87J+FDIz4WIzo0EkAvrwgAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AFRzoVR3nvhP+FeBAQv0CpL0BZFt4oEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfJgLiVHi9VhT4TvhXgQEL9AqS9AWRbeKBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkEWXed7Oy3/Lf8t/VVDIzst/y3/Lf1nIzst/zc3JI8IAIJQwIsIA3o6AjoDiXwUzJwIQI8IAjoCOgOIuKAIQIsIAjoCOgOIsKQH+LPhO+FVcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4dfhPAVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RB+HX4TvhWXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+Hb4TwFcgQEL9AqS9AWRbeIjAYEBCyoB8vRZMMj0AFmBAQv0Qfh2+E74V1yBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh3+E8BXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EH4dzBTxPhP+FOBAQv0CpPXC3+RcOL4TvhTgQEL9AqT1wt/kXDiU7wrAICL3AAAAAAAAAAAAAAAABjIzlVQyM+RXFEwYst/y3/Lf8t/y38ByM7Nzclw+wAsyM+FiM5xzwtuIc8UyYEAgPsAAeLIIHd3jQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEd1UEywfOzst/y38xIMlUcE74T/hXgQEL9AqS9AWRbeKBAQv0Ci0B/o4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkTr7/UbOy3/MyfhP+FiBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPhYjOjQSQF9eEAAAAAAAAAAAAAAAAAADAzxYwAeLIIHd3jQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEd1UEywfOzst/y38xIMlUcF74TvhXgQEL9AqS9AWRbeKBAQv0Ci8B/o4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkTr7/UbOy3/MyfhO+FiBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPhYjOjQSQF9eEAAAAAAAAAAAAAAAAAADAzxYwAfwhzxTJcPsAL/hO+FVcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4dfhPAVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RB+HX4TvhWXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+Hb4TwFcgQEL9AqS9AUxAf6RbeIjAYEBC/RZMMj0AFmBAQv0Qfh2+E74V1yBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh3+E8BXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EH4dzBT9/hP+FOBAQv0CpPXC3+RcOL4TvhTgQEL9AqT1wt/kXDiMgCIU++L3AAAAAAAAAAAAAAAABjIzlVQyM+RXFEwYst/y3/Lf8t/y38ByM7Nzclw+wAvyM+FiM5xzwtuJM8UyYEAgPsAXwMB4sggd3eNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR3VQTLB87Oy3/LfzEgyVRwXvhO+FeBAQv0CpL0BZFt4oEBC/QKNAH+jiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+ROvv9Rs7Lf8zJVHFf+E/4V4EBC/QKkvQFkW3igQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz5E6+/1Gzst/zMn4TjUBtPhYgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz4WIzo0EkBfXhAAAAAAAAAAAAAAAAAAAwM8WIs8UyXD7APhP+FiBAQv0CjYB/o4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPhYjOjQSQF9eEAAAAAAAAAAAAAAAAAADAzxYhzxTJcPsAVhD4TvhVXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+HX4TwFcgQEL9AqS9AWRbeI3Af4jAYEBC/RZMMj0AFmBAQv0Qfh1+E74VlyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh2+E8BXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EH4dvhO+FdcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4d/hPOAH+AVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RB+HcwVhAp+E/4U4EBC/QKk9cLf5Fw4vhO+FOBAQv0CpPXC3+RcOIvVhGL3AAAAAAAAAAAAAAAABjIzlVQyM+RXFEwYst/y3/Lf8t/y38ByM7Nzclw+wBWEMjPhYjOcc8LbjkAFiXPFMmBAID7AF8EAf5ctggi+E74U1yBAQv0CpPXC3+RcOJVAqC1f8jLf1mBAQv0QfhzIfhP+FNcgQEL9AqT1wt/kXDiVQKgtX/Iy39ZgQEL9EH4c/hUIaC1f/h0U1DIz5HI9xM6y3/OyfhQyM+FiM6NBJAL68IAAAAAAAAAAAAAAAAAAMDPFiHPFMlwOwH8+wAn+E74VVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh1+E8BXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EH4dfhO+FZcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4dvhPAVyBAQv0CpL0BZFt4iMBPAHkgQEL9FkwyPQAWYEBC/RB+Hb4TvhXXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+Hf4TwFcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0Qfh3MFMWcFR1WvhP+FeBAQv0CpL0BZFt4oEBC/QKPQH+jiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfcFR6rvhO+FeBAQv0CpL0BZFt4oEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+QRZd53s7Lf8t/y39VUMjOy3/Lf8t/WT4A2sjOy3/NzclTgvhP+FOBAQv0CpPXC3+RcOL4TvhTgQEL9AqT1wt/kXDiU3iL3AAAAAAAAAAAAAAAABjIzlVQyM+RXFEwYst/y3/Lf8t/y38ByM7Nzclw+wAoyM+FiM5xzwtuIc8UyYEAgPsAXwMDxi7bPFPvXyKBA+WotX9TAfhTgQEL9AqT1wt/kXDiqLV/UxP4U4EBC/QKk9cLf5Fw4oED6Ki1f6C1f3FfIqmEtX9sYVMB+FOBAQv0CpPXC3+RcOK7IJswUwO+IJQwUwK73t6OgERBQADejmvIUwFWEihWEXhVBMsHzs7Lf8t/MSDJIFYSVhDIz5E6+/1Gzst/zMlWE/hYgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz4WIznHPC24hzxTJgQCA+wBfA+JbAf4vVhH4U1yBAQv0CpPXC3+RcOJVAqC1f8jLf1mBAQv0QfhzUwH4U1yBAQv0CpPXC3+RcOJVAqG1f8jLf1mBAQv0QfhzVhD4UlYS+FOBAQv0CpPXC3+RcOItupF/kXDiyMoAWYEBC/RB+HLIUwFWEihWEXBVBMsHzs7Lf8t/MSDJQgHWVHAmyM+ROvv9Rs7Lf8zJKFYUJvhTgQEL9AqT1wt/kXDiVhb4U4EBC/QKk9cLf5Fw4idWF4vcAAAAAAAAAAAAAAAAGMjOVVDIz5CBqKN2y3/Lf8t/y39ZyM4ByM7Nzc3JcPsAJPhYgQEL9ApDAHaOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz4WIznHPC24hzxTJgQCA+wBfAwAaIPhOxwWS+E+S+E7iMQFSMNHbPPhXIY4cjQRwAAAAAAAAAAAAAAAANkPf1aDIzvQAyXD7AN5/+GeEAVAw0ds8+E4hjhuNBHAAAAAAAAAAAAAAAAA1g30KYMjOzslw+wDef/hnhAFQMNHbPPhPIY4bjQRwAAAAAAAAAAAAAAAANMU3pSDIzs7JcPsA3n/4Z4QEUCCCEBh1ArG74wIgghAypoThu+MCIIIQPMkQPrvjAiCCEFHvZT+74wJ/Z09JBFAgghA+7hMquuMCIIIQQH5mgbrjAiCCEEbyakq64wIgghBR72U/uuMCTk1LSgFQMNHbPPhKIY4bjQRwAAAAAAAAAAAAAAAANHvZT+DIzs7JcPsA3n/4Z4QD8jD4Qm7jANMf+ERYb3X4ZNcN/5XU0dDT/9/R2zwhjh8j0NMB+kAwMcjPhyDOcc8LYQHIz5Mbyakqzs3JcPsAjjP4RCBvEyFvEvhJVQJvEchyz0DKAHPPQM4B+gL0AHHPC2kByPhEbxXPCx/Ozcn4RG8U+wDi4wB/+GeETHYAlvhEcG9ycG9xgEBvdPhkIG34QsjL/3BYgED0QyHIy/9xWIBA9EP4KHJYgED0Fsj0AMn4TcjPhID0APQAz4HJ+QDIz4oAQMv/ydAxMQFSMNHbPPhZIY4cjQRwAAAAAAAAAAAAAAAAMB+ZoGDIzvQAyXD7AN5/+GeEAVAw0ds8+EwhjhuNBHAAAAAAAAAAAAAAAAAvu4TKoMjOzslw+wDef/hnhARQIIIQMzalUrrjAiCCEDfqILO64wIgghA4fj3kuuMCIIIQPMkQPrrjAmZlZFADmDD4Qm7jANcNf5XU0dDTf98g10vAAQHAALCT1NHQ3tTXDf+V1NHQ0//f+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf0ds82zx/+GeEUXYBMvgnbxBopv5gobV/cvsC+En4UMcFjoDeXwZSBP4k0CDTB/pA+kDTf9N/Nvha+FuBAQD0D46AjoDiKG9Q+ElvUSxvUipvUylvVChvVY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABG9WcG9XJW9YJG9ZI29aIm9bIW9c+Fr4WyLbPMlZgQEA9Bf4e/hapCD4esIKYl9eUwLKjoDeJcADII5WMCSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATHBbMgjikwI40IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFs97ejoDeXwdaVAG6+E74U4EBC/QKk9cLf5Fw4i34VKmEtX/4T/hTgQEL9AqT1wt/kXDiLvhUqYS1fyH4TvhTgQEL9AqT1wt/kXDivLMgjhQwIPhP+FOBAQv0CpPXC3+RcOK8s96OgN5bVQHo+FQvobV/+HQh+E74U1yBAQv0CpPXC3+RcOJVAqG1f8jLf1mBAQv0QfhzIPhP+FNcgQEL9AqT1wt/kXDiVQKhtX/Iy39ZgQEL9EH4c8ggdnaNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARWAf6NCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR2VQTLB87Oy3/LfzEgyVRwOMjPkTr7/UbOy3/MyVRxOMjPkTr7/UbOy3/MyfhO+FiBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEVwH+38jPhYjOjQSQL68IAAAAAAAAAAAAAAAAAADAzxYizxTJcPsA+E/4WIEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+FiM6NBJAvrwgAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBUdJUtVhZWE1gB/sjPkXhFhcbOy39VMMjOy39ZyM7Lf83NyS74T/hTgQEL9AqT1wt/kXDi+E74U4EBC/QKk9cLf5Fw4lOJ+FRWGYvcAAAAAAAAAAAAAAAAGMjOVWDIz5B+acjay3/Lf8t/y3/Lf8t/AcjOzc3JcPsALsjPhYjOcc8LbiHPFMmBAIBZAAj7AF8FARr4W9s8AYEBAPRbMPh7WwEIcI6A2FwBRvhbgQEA9IdvoYreIG6zml8gbvJ/byIhbEGVcGwSATDjBNkwXQEMAdDbPG8CYwBgby1esMjOVbDIzst/y/9VgMjOVXDIzlVgyM7Lf8sHVTDIzlUgyM7Lf8t/zc3Nzc3NAdyNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARwcI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABGAB3I0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEYQBQjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvDQEG0Ns8YwDu+kD6QZXU0dD6QN/XDX+V1NHQ03/f1w3/ldTR0NP/3/pBldTR0PpA3/pBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDQeV1NHQ0wff+kGV1NHQ+kDf+kGV1NHQ+kDf1w1/ldTR0NN/39cNf5XU0dDTf9/Rbw0BUjDR2zz4WyGOHI0EcAAAAAAAAAAAAAAAAC4fj3kgyM70AMlw+wDef/hnhAFSMNHbPPhaIY4cjQRwAAAAAAAAAAAAAAAALfqILODIzsv/yXD7AN5/+GeEAVIw0ds8+EshjhyNBHAAAAAAAAAAAAAAAAAszalUoMjOy//JcPsA3n/4Z4QEUCCCECxl2Q+64wIgghAuVzCnuuMCIIIQMgJViLrjAiCCEDKmhOG64wJ1dGloAVAw0ds8+E0hjhuNBHAAAAAAAAAAAAAAAAAsqaE4YMjOzMlw+wDef/hnhAP8MPhCbuMA+Ebyc3/4ZtcN/5XU0dDT/9/XDf+V1NHQ0//f1w1/ldTR0NN/39cNf5XU0dDTf9/R+En4SscF8uBm+ABw+Hr4TiRdbfhCyMv/cFiAQPRDI8jL/3FYgED0Q/gocliAQPQWyPQAyfhNyM+EgPQA9ADPgcmIUxH5APgob25qA/76Qm8SyM+GQMoHy//J0AFTUcjPhYjOAfoCi9AAAAAAAAAAAAAAAAAHzxbMz4MizxTJcPsAIPhZgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+Inb1Amb1Fwb1Ih+Fki2zzJWYEBC/QTfXprAuz4eSfIz5C6I4sSzslTUsjPhYjOAfoCcc8LaiHPFMlw+wBfCfhPXzNt+ELIy/9wWIBA9EMjyMv/cViAQPRD+ChyWIBA9BbI9ADJ+E3Iz4SA9AD0AM+ByYhTEfkA+Cj6Qm8SyM+GQMoHy//J0AFTUcjPhYjOAfoCbmwD+ovQAAAAAAAAAAAAAAAAB88WzM+DIs8UyXD7ACD4WYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiJ29QJm9RcG9SIfhZIts8yVmBAQv0E/h5J8jPkLojixLOyVNSyM+FiM4B+gJxfXptAZ7PC2ohzxTJcPsAXwn4UPhP+E7Iz5HcmCl2zlnIzgHIzs3NyfhKyM+FiM6NBJB3NZQAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBfBds8f/hndgAIaLVfPwIW7UTQ10nCAYqOgOKEcAL+cO1E0PQFcSGAQPQOjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+GpyIYBA9A6T1wv/kXDi+GtzIYBA9A6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4bHQhgED0D46A3/htdXNxAcYhgED0Do4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hudiGAQPQOjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+G93IYBA9A5yALaOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4cG34cW34cm34c3D4dG34dW34dm34d234eG34eXD4em34e4BA9A7yvdcL//hicPhjcPhmAQKIhwFSMNHbPPhVIY4cjQRwAAAAAAAAAAAAAAAAK5XMKeDIzvQAyXD7AN5/+GeEAy4w+EJu4wD6QZXU0dD6QN/R2zzbPH/4Z4R3dgDY+Fv4WvhZ+Fj4V/hW+FX4VPhT+FL4UfhQ+E/4TvhN+Ez4S/hK+Eb4Q/hCyMv/yz/KAM6AEXFjyMv/zsxV0MjOVcDIzlWwyM70APQA9ADLf1VgyPQA9AD0AFUwyPQA9ADL//QAzc3Nzc3Nye1UAWD4SfhZgQEL9AogkTHe8uBt+CdvEGim/mChtX9y+wL4SSD4WYEBC/QKIJEx3o6A3lt4A9gg+FmBAQv0C46AjiiNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARwcG8D4vhRIW8QASRZgQEL9BL4cfhSIW8QAX/IygBZgQEL9EH4cvhYIW8QASNZgQEL9BL4eIgiyM+FiM59fHkCso0EkHc1lAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AIgjyM+FiM6NBJB3NZQAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wAif29SMyP4WSTbPMlZgQEL9BP4eV8De3oAEm8jAsjOy//KAAAIYBgiCAAICHAcnQEG0Ns8fgAS+kDT/9IA0W8DBFAgghAFvCgKuuMCIIIQB/0oy7rjAiCCEA8OUIq64wIgghAYdQKxuuMCg4KBgAFSMNHbPPhSIY4cjQRwAAAAAAAAAAAAAAAAJh1ArGDIzvQAyXD7AN5/+GeEAVIw0ds8+FghjhyNBHAAAAAAAAAAAAAAAAAjw5QioMjO9ADJcPsA3n/4Z4QBUjDR2zz4UyGOHI0EcAAAAAAAAAAAAAAAACH/SjLgyM70AMlw+wDef/hnhAFSMNHbPPhRIY4cjQRwAAAAAAAAAAAAAAAAIW8KAqDIzvQAyXD7AN5/+GeEANLtRNDT/9M/0gD6QNTR0NP/+kDU1NHQ+kDU0dD6QNTR0PpA9AT0BPQE03/U0dD0BPQE9ATU0dD0BPQE0//0BNH4e/h6+Hn4ePh3+Hb4dfh0+HP4cvhx+HD4b/hu+G34bPhr+Gr4Zvhj+GICCvSkIPShh4YAFHNvbCAwLjQ3LjAAAA==",
		code: "te6ccgEChQEAJ2EABCSK7VMg4wMgwP/jAiDA/uMC8guCAwGEAQACAviNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAT4aSHbPNMAAY4agQIA1xgg+QEB0wABlNP/AwGTAvhC4vkQ8qiV0wAB8nri0z8B+EMhufK0IPgjgQPoqIIIG3dAoLnytPhj0x8B+CO88rnTHwHbPPhHbvJ8bAQBaiLQ0wP6QDD4aak4APhEf29xggiYloBvcm1vc3BvdPhk3CHHANwh1w0f8rwh3QHbPPhHbvJ8BAIoIIIQUe9lP7vjAiCCEHtXi/a74wJFBQM8IIIQWUEfubvjAiCCEHhUQh+74wIgghB7V4v2uuMCDwgGAuIw0x/4RFhvdfhk0ds8IY4oI9DTAfpAMDHIz4cgzo0EAAAAAAAAAAAAAAAAD7V4v2jPFst/yXD7AI4x+EQgbxMhbxL4SVUCbxHIcs9AygBzz0DOAfoC9ACAas9A+ERvFc8LH8t/yfhEbxT7AOLjAH/4ZwdzACT4RHBvcnBvcYBAb3T4ZPgnbxAEUCCCEGLFruu64wIgghBkOy/CuuMCIIIQbwUweLrjAiCCEHhUQh+64wIMCwoJAVIw0ds8+FQhjhyNBHAAAAAAAAAAAAAAAAA+FRCH4MjOy3/JcPsA3n/4Z4EBUjDR2zz4ViGOHI0EcAAAAAAAAAAAAAAAADvBTB4gyM70AMlw+wDef/hngQFQMNHbPPhQIY4bjQRwAAAAAAAAAAAAAAAAOQ7L8KDIzs7JcPsA3n/4Z4EDHDD4Qm7jANHbPNs8f/hngQ1zAfz4SfgnbxBopv5gobV/cvsC+FD4T/hRgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4T/hO+FGBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hOyM+RU/cVIs4OAE5VMMjOVSDIzlnIzgHIzs3Nzc3JIcjPhYjOcc8LbiHPFMmBAID7AFsEUCCCEFMU3pS64wIgghBWDfQpuuMCIIIQWQ9/VrrjAiCCEFlBH7m64wJEQ0IQA7Qw+EJu4wD6QZXU0dD6QN/6QZXU0dD6QN/XDX+V1NHQ03/f1w3/ldTR0NP/3/pBldTR0PpA3/pBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/U0ds82zx/+GeBEXMC/PgnbxBopv5gobV/cvsC+En4TvhRgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/HBSCONTD4SfhP+FGBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38cF346A3hMSAARfCQTK+Fr4W4EBAPQPjoCOgOIpb1Aob1Enb1Imb1Mlb1Qkb1Ujb1Yib1ch0CDTB/pA+kDTf9N/NlNkb1g3U2NvWTdTYm9aN1Nhb1s3U2BvXDf4WvhbKNs8yVmBAQD0F/h7+FqkIPh6wgpfXFsUAyKOgN4kwAGOgN4kwAKOgN5fB1c8FQH+LvhVXIEBC/QKkvQFkW3iJgF/yMoAWYEBC/RByPQAWYEBC/RB+HVT3vhWXIEBC/QKkvQFkW3iJwFcgQEL9AqT1wt/kXDiVQSgtX/Iy39ZgQEL9EHI9ABZgQEL9EH4di74V1yBAQv0CpL0BZFt4iYBLlmBAQv0Esj0AFmBAQv0QRYBsPh3I/hO+FWBAQv0CpL0BZFt4oEBC/QKk9cKAJFw4n+6II4fMCP4T/hVgQEL9AqS9AWRbeKBAQv0CpPXCgCRcOJ/ut6OgI4QI8jPhYjOgG/PQMmBAID7AOIXAuAj+E74VoEBC/QKkvQFkW3igQEL9AqT1wt/kXDiJPhP+FaBAQv0CpL0BZFt4oEBC/QKk9cLf5Fw4vhUwAAgjiow+E74U4EBC/QKk9cLf5Fw4sAAII4TMPhP+FOBAQv0CpPXC3+RcOLAAN/fjoCOgOJbNxgB/l8xIPhP+FOBAQv0CpPXC3+RcOL4TvhTgQEL9AqT1wt/kXDiqYS1fzFTEfhO+FOBAQv0CpPXC3+RcOL4T/hTgQEL9AqT1wt/kXDiqYS1fzFTMLYIXbYI+E74U4EBC/QKk9cLf5Fw4vhP+FOBAQv0CpPXC3+RcOK2CPhO+FOBAQsZAtj0CpPXC3+RcOL4T/hTgQEL9AqT1wt/kXDitglccVMSqYwBtX8BIWxBXyJxUxKpjAG1fwEgbEFfJbYIUwKotX9UcSWphLV/oLV/Xye5kSGRIOJTeLmRIpEh4lxs4iHCACCUMCDCAN6OgI6A4lshGgHiyCB5eY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHlVBMsHzs7Lf8t/MSDJVHBZ+E74V4EBC/QKkvQFkW3igQEL9AobAf6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz5E6+/1Gzst/zMlUcVr4T/hXgQEL9AqS9AWRbeKBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkTr7/UbOy3/MyfhOHAG0+FiBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPhYjOjQSQF9eEAAAAAAAAAAAAAAAAAADAzxYizxTJcPsA+E/4WIEBC/QKHQH+jiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+FiM6NBJAX14QAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wAr+E74VVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh1+E8BXIEBC/QKkvQFkW3iIx4B/gGBAQv0WTDI9ABZgQEL9EH4dfhO+FZcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4dvhPAVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RB+Hb4TvhXXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+Hf4TwEfAfRcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0Qfh3MHBTt3BTr/hP+FeBAQv0CpL0BZFt4oEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfLXAvVhT4TvhXgQEL9AqS9AWRbeKBAQv0CiAAuI4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkEWXed7Oy3/Lf8t/VVDIzst/y3/Lf1nIzst/zc3JLMjPhYjOcc8LbiHPFMmBAID7AF8FAfxTEfhU+E74U4EBC/QKk9cLf5Fw4qmEtX8xUxH4VPhP+FOBAQv0CpPXC3+RcOKphLV/MbYIU0KhtX9TQqG1fyT4TvhTXIEBC/QKk9cLf5Fw4lUCoLV/yMt/WYEBC/RB+HMj+E/4U1yBAQv0CpPXC3+RcOJVAqC1f8jLf1mBAQsiAf70Qfhz+FQjoLV/+HRTksjPkcj3EzrLf87J+FDIz4WIzo0EkAvrwgAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AFRzoVR3nvhP+FeBAQv0CpL0BZFt4oEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfIwLiVHi9VhT4TvhXgQEL9AqS9AWRbeKBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkEWXed7Oy3/Lf8t/VVDIzst/y3/Lf1nIzst/zc3JI8IAIJQwIsIA3o6AjoDiXwUwJAIQI8IAjoCOgOIrJQIQIsIAjoCOgOIpJgH+LPhO+FVcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4dfhPAVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RB+HX4TvhWXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+Hb4TwFcgQEL9AqS9AWRbeIjAYEBCycB8vRZMMj0AFmBAQv0Qfh2+E74V1yBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh3+E8BXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EH4dzBTxPhP+FOBAQv0CpPXC3+RcOL4TvhTgQEL9AqT1wt/kXDiU7woAICL3AAAAAAAAAAAAAAAABjIzlVQyM+RXFEwYst/y3/Lf8t/y38ByM7Nzclw+wAsyM+FiM5xzwtuIc8UyYEAgPsAAeLIIHd3jQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEd1UEywfOzst/y38xIMlUcE74T/hXgQEL9AqS9AWRbeKBAQv0CioB/o4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkTr7/UbOy3/MyfhP+FiBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPhYjOjQSQF9eEAAAAAAAAAAAAAAAAAADAzxYtAeLIIHd3jQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEd1UEywfOzst/y38xIMlUcF74TvhXgQEL9AqS9AWRbeKBAQv0CiwB/o4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPkTr7/UbOy3/MyfhO+FiBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPhYjOjQSQF9eEAAAAAAAAAAAAAAAAAADAzxYtAfwhzxTJcPsAL/hO+FVcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4dfhPAVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RB+HX4TvhWXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+Hb4TwFcgQEL9AqS9AUuAf6RbeIjAYEBC/RZMMj0AFmBAQv0Qfh2+E74V1yBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh3+E8BXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EH4dzBT9/hP+FOBAQv0CpPXC3+RcOL4TvhTgQEL9AqT1wt/kXDiLwCIU++L3AAAAAAAAAAAAAAAABjIzlVQyM+RXFEwYst/y3/Lf8t/y38ByM7Nzclw+wAvyM+FiM5xzwtuJM8UyYEAgPsAXwMB4sggd3eNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR3VQTLB87Oy3/LfzEgyVRwXvhO+FeBAQv0CpL0BZFt4oEBC/QKMQH+jiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+ROvv9Rs7Lf8zJVHFf+E/4V4EBC/QKkvQFkW3igQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz5E6+/1Gzst/zMn4TjIBtPhYgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz4WIzo0EkBfXhAAAAAAAAAAAAAAAAAAAwM8WIs8UyXD7APhP+FiBAQv0CjMB/o4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE38jPhYjOjQSQF9eEAAAAAAAAAAAAAAAAAADAzxYhzxTJcPsAVhD4TvhVXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+HX4TwFcgQEL9AqS9AWRbeI0Af4jAYEBC/RZMMj0AFmBAQv0Qfh1+E74VlyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh2+E8BXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EH4dvhO+FdcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4d/hPNQH+AVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RB+HcwVhAp+E/4U4EBC/QKk9cLf5Fw4vhO+FOBAQv0CpPXC3+RcOIvVhGL3AAAAAAAAAAAAAAAABjIzlVQyM+RXFEwYst/y3/Lf8t/y38ByM7Nzclw+wBWEMjPhYjOcc8LbjYAFiXPFMmBAID7AF8EAf5ctggi+E74U1yBAQv0CpPXC3+RcOJVAqC1f8jLf1mBAQv0QfhzIfhP+FNcgQEL9AqT1wt/kXDiVQKgtX/Iy39ZgQEL9EH4c/hUIaC1f/h0U1DIz5HI9xM6y3/OyfhQyM+FiM6NBJAL68IAAAAAAAAAAAAAAAAAAMDPFiHPFMlwOAH8+wAn+E74VVyBAQv0CpL0BZFt4iMBgQEL9FkwyPQAWYEBC/RBIPh1+E8BXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EH4dfhO+FZcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0QSD4dvhPAVyBAQv0CpL0BZFt4iMBOQHkgQEL9FkwyPQAWYEBC/RB+Hb4TvhXXIEBC/QKkvQFkW3iIwGBAQv0WTDI9ABZgQEL9EEg+Hf4TwFcgQEL9AqS9AWRbeIjAYEBC/RZMMj0AFmBAQv0Qfh3MFMWcFR1WvhP+FeBAQv0CpL0BZFt4oEBC/QKOgH+jiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfcFR6rvhO+FeBAQv0CpL0BZFt4oEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+QRZd53s7Lf8t/y39VUMjOy3/Lf8t/WTsA2sjOy3/NzclTgvhP+FOBAQv0CpPXC3+RcOL4TvhTgQEL9AqT1wt/kXDiU3iL3AAAAAAAAAAAAAAAABjIzlVQyM+RXFEwYst/y3/Lf8t/y38ByM7Nzclw+wAoyM+FiM5xzwtuIc8UyYEAgPsAXwMDxi7bPFPvXyKBA+WotX9TAfhTgQEL9AqT1wt/kXDiqLV/UxP4U4EBC/QKk9cLf5Fw4oED6Ki1f6C1f3FfIqmEtX9sYVMB+FOBAQv0CpPXC3+RcOK7IJswUwO+IJQwUwK73t6OgEE+PQDejmvIUwFWEihWEXhVBMsHzs7Lf8t/MSDJIFYSVhDIz5E6+/1Gzst/zMlWE/hYgQEL9AqOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz4WIznHPC24hzxTJgQCA+wBfA+JbAf4vVhH4U1yBAQv0CpPXC3+RcOJVAqC1f8jLf1mBAQv0QfhzUwH4U1yBAQv0CpPXC3+RcOJVAqG1f8jLf1mBAQv0QfhzVhD4UlYS+FOBAQv0CpPXC3+RcOItupF/kXDiyMoAWYEBC/RB+HLIUwFWEihWEXBVBMsHzs7Lf8t/MSDJPwHWVHAmyM+ROvv9Rs7Lf8zJKFYUJvhTgQEL9AqT1wt/kXDiVhb4U4EBC/QKk9cLf5Fw4idWF4vcAAAAAAAAAAAAAAAAGMjOVVDIz5CBqKN2y3/Lf8t/y39ZyM4ByM7Nzc3JcPsAJPhYgQEL9ApAAHaOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/Iz4WIznHPC24hzxTJgQCA+wBfAwAaIPhOxwWS+E+S+E7iMQFSMNHbPPhXIY4cjQRwAAAAAAAAAAAAAAAANkPf1aDIzvQAyXD7AN5/+GeBAVAw0ds8+E4hjhuNBHAAAAAAAAAAAAAAAAA1g30KYMjOzslw+wDef/hngQFQMNHbPPhPIY4bjQRwAAAAAAAAAAAAAAAANMU3pSDIzs7JcPsA3n/4Z4EEUCCCEBh1ArG74wIgghAypoThu+MCIIIQPMkQPrvjAiCCEFHvZT+74wJ8ZExGBFAgghA+7hMquuMCIIIQQH5mgbrjAiCCEEbyakq64wIgghBR72U/uuMCS0pIRwFQMNHbPPhKIY4bjQRwAAAAAAAAAAAAAAAANHvZT+DIzs7JcPsA3n/4Z4ED8jD4Qm7jANMf+ERYb3X4ZNcN/5XU0dDT/9/R2zwhjh8j0NMB+kAwMcjPhyDOcc8LYQHIz5Mbyakqzs3JcPsAjjP4RCBvEyFvEvhJVQJvEchyz0DKAHPPQM4B+gL0AHHPC2kByPhEbxXPCx/Ozcn4RG8U+wDi4wB/+GeBSXMAlvhEcG9ycG9xgEBvdPhkIG34QsjL/3BYgED0QyHIy/9xWIBA9EP4KHJYgED0Fsj0AMn4TcjPhID0APQAz4HJ+QDIz4oAQMv/ydAxMQFSMNHbPPhZIY4cjQRwAAAAAAAAAAAAAAAAMB+ZoGDIzvQAyXD7AN5/+GeBAVAw0ds8+EwhjhuNBHAAAAAAAAAAAAAAAAAvu4TKoMjOzslw+wDef/hngQRQIIIQMzalUrrjAiCCEDfqILO64wIgghA4fj3kuuMCIIIQPMkQPrrjAmNiYU0DmDD4Qm7jANcNf5XU0dDTf98g10vAAQHAALCT1NHQ3tTXDf+V1NHQ0//f+kGV1NHQ+kDf+kGV1NHQ+kDf+kGV1NHQ+kDf0ds82zx/+GeBTnMBMvgnbxBopv5gobV/cvsC+En4UMcFjoDeXwZPBP4k0CDTB/pA+kDTf9N/Nvha+FuBAQD0D46AjoDiKG9Q+ElvUSxvUipvUylvVChvVY0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABG9WcG9XJW9YJG9ZI29aIm9bIW9c+Fr4WyLbPMlZgQEA9Bf4e/hapCD4esIKX1xbUALKjoDeJcADII5WMCSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATHBbMgjikwI40IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMcFs97ejoDeXwdXUQG6+E74U4EBC/QKk9cLf5Fw4i34VKmEtX/4T/hTgQEL9AqT1wt/kXDiLvhUqYS1fyH4TvhTgQEL9AqT1wt/kXDivLMgjhQwIPhP+FOBAQv0CpPXC3+RcOK8s96OgN5bUgHo+FQvobV/+HQh+E74U1yBAQv0CpPXC3+RcOJVAqG1f8jLf1mBAQv0QfhzIPhP+FNcgQEL9AqT1wt/kXDiVQKhtX/Iy39ZgQEL9EH4c8ggdnaNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARTAf6NCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAR2VQTLB87Oy3/LfzEgyVRwOMjPkTr7/UbOy3/MyVRxOMjPkTr7/UbOy3/MyfhO+FiBAQv0Co4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEVAH+38jPhYjOjQSQL68IAAAAAAAAAAAAAAAAAADAzxYizxTJcPsA+E/4WIEBC/QKjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATfyM+FiM6NBJAvrwgAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBUdJUtVhZWE1UB/sjPkXhFhcbOy39VMMjOy39ZyM7Lf83NyS74T/hTgQEL9AqT1wt/kXDi+E74U4EBC/QKk9cLf5Fw4lOJ+FRWGYvcAAAAAAAAAAAAAAAAGMjOVWDIz5B+acjay3/Lf8t/y3/Lf8t/AcjOzc3JcPsALsjPhYjOcc8LbiHPFMmBAIBWAAj7AF8FARr4W9s8AYEBAPRbMPh7WAEIcI6A2FkBRvhbgQEA9IdvoYreIG6zml8gbvJ/byIhbEGVcGwSATDjBNkwWgEMAdDbPG8CYABgby1esMjOVbDIzst/y/9VgMjOVXDIzlVgyM7Lf8sHVTDIzlUgyM7Lf8t/zc3Nzc3NAdyNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARwcI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABF0B3I0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEXgBQjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvDQEG0Ns8YADu+kD6QZXU0dD6QN/XDX+V1NHQ03/f1w3/ldTR0NP/3/pBldTR0PpA3/pBldTR0PpA3/pBldTR0PpA39cNf5XU0dDTf9/XDQeV1NHQ0wff+kGV1NHQ+kDf+kGV1NHQ+kDf1w1/ldTR0NN/39cNf5XU0dDTf9/Rbw0BUjDR2zz4WyGOHI0EcAAAAAAAAAAAAAAAAC4fj3kgyM70AMlw+wDef/hngQFSMNHbPPhaIY4cjQRwAAAAAAAAAAAAAAAALfqILODIzsv/yXD7AN5/+GeBAVIw0ds8+EshjhyNBHAAAAAAAAAAAAAAAAAszalUoMjOy//JcPsA3n/4Z4EEUCCCECxl2Q+64wIgghAuVzCnuuMCIIIQMgJViLrjAiCCEDKmhOG64wJycWZlAVAw0ds8+E0hjhuNBHAAAAAAAAAAAAAAAAAsqaE4YMjOzMlw+wDef/hngQP8MPhCbuMA+Ebyc3/4ZtcN/5XU0dDT/9/XDf+V1NHQ0//f1w1/ldTR0NN/39cNf5XU0dDTf9/R+En4SscF8uBm+ABw+Hr4TiRdbfhCyMv/cFiAQPRDI8jL/3FYgED0Q/gocliAQPQWyPQAyfhNyM+EgPQA9ADPgcmIUxH5APgobGtnA/76Qm8SyM+GQMoHy//J0AFTUcjPhYjOAfoCi9AAAAAAAAAAAAAAAAAHzxbMz4MizxTJcPsAIPhZgQEL9AuOgI4ojQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEcHBvA+Inb1Amb1Fwb1Ih+Fki2zzJWYEBC/QTendoAuz4eSfIz5C6I4sSzslTUsjPhYjOAfoCcc8LaiHPFMlw+wBfCfhPXzNt+ELIy/9wWIBA9EMjyMv/cViAQPRD+ChyWIBA9BbI9ADJ+E3Iz4SA9AD0AM+ByYhTEfkA+Cj6Qm8SyM+GQMoHy//J0AFTUcjPhYjOAfoCa2kD+ovQAAAAAAAAAAAAAAAAB88WzM+DIs8UyXD7ACD4WYEBC/QLjoCOKI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHBwbwPiJ29QJm9RcG9SIfhZIts8yVmBAQv0E/h5J8jPkLojixLOyVNSyM+FiM4B+gJxendqAZ7PC2ohzxTJcPsAXwn4UPhP+E7Iz5HcmCl2zlnIzgHIzs3NyfhKyM+FiM6NBJB3NZQAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wBfBds8f/hncwAIaLVfPwIW7UTQ10nCAYqOgOKBbQL+cO1E0PQFcSGAQPQOjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+GpyIYBA9A6T1wv/kXDi+GtzIYBA9A6OJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4bHQhgED0D46A3/htdXBuAcYhgED0Do4kjQhgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAE3/hudiGAQPQOjiSNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATf+G93IYBA9A5vALaOJI0IYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABN/4cG34cW34cm34c3D4dG34dW34dm34d234eG34eXD4em34e4BA9A7yvdcL//hicPhjcPhmAQKIhAFSMNHbPPhVIY4cjQRwAAAAAAAAAAAAAAAAK5XMKeDIzvQAyXD7AN5/+GeBAy4w+EJu4wD6QZXU0dD6QN/R2zzbPH/4Z4F0cwDY+Fv4WvhZ+Fj4V/hW+FX4VPhT+FL4UfhQ+E/4TvhN+Ez4S/hK+Eb4Q/hCyMv/yz/KAM6AEXFjyMv/zsxV0MjOVcDIzlWwyM70APQA9ADLf1VgyPQA9AD0AFUwyPQA9ADL//QAzc3Nzc3Nye1UAWD4SfhZgQEL9AogkTHe8uBt+CdvEGim/mChtX9y+wL4SSD4WYEBC/QKIJEx3o6A3lt1A9gg+FmBAQv0C46AjiiNCGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARwcG8D4vhRIW8QASRZgQEL9BL4cfhSIW8QAX/IygBZgQEL9EH4cvhYIW8QASNZgQEL9BL4eIgiyM+FiM56eXYCso0EkHc1lAAAAAAAAAAAAAAAAAAAwM8WIc8UyXD7AIgjyM+FiM6NBJB3NZQAAAAAAAAAAAAAAAAAAMDPFiHPFMlw+wAif29SMyP4WSTbPMlZgQEL9BP4eV8DeHcAEm8jAsjOy//KAAAIYBgiCAAICHAcnQEG0Ns8ewAS+kDT/9IA0W8DBFAgghAFvCgKuuMCIIIQB/0oy7rjAiCCEA8OUIq64wIgghAYdQKxuuMCgH9+fQFSMNHbPPhSIY4cjQRwAAAAAAAAAAAAAAAAJh1ArGDIzvQAyXD7AN5/+GeBAVIw0ds8+FghjhyNBHAAAAAAAAAAAAAAAAAjw5QioMjO9ADJcPsA3n/4Z4EBUjDR2zz4UyGOHI0EcAAAAAAAAAAAAAAAACH/SjLgyM70AMlw+wDef/hngQFSMNHbPPhRIY4cjQRwAAAAAAAAAAAAAAAAIW8KAqDIzvQAyXD7AN5/+GeBANLtRNDT/9M/0gD6QNTR0NP/+kDU1NHQ+kDU0dD6QNTR0PpA9AT0BPQE03/U0dD0BPQE9ATU0dD0BPQE0//0BNH4e/h6+Hn4ePh3+Hb4dfh0+HP4cvhx+HD4b/hu+G34bPhr+Gr4Zvhj+GICCvSkIPShhIMAFHNvbCAwLjQ3LjAAAA==",
	},
};
